Add french readme + fixes
YunoHost-Apps/funkwhale_ynh pull request #123
Opened 2020-12-14 20:44 UTC by Thovi98

2020-12-14 20:46 UTC, Thovi98 commented
Oww I see I did not take te latest version of the Readme, I will update soon.

2020-12-14 21:06 UTC, Thovi98 commented
So now I think it’s okay, don’t hesitate to check if I let some mistakes.

2020-12-14 21:08 UTC, ericgaspar requested changes

2020-12-14 21:08 UTC, ericgaspar commented on README.md
> +----------------
```suggestion
## Developers info
```
Same result, but to keep consistency

2020-12-14 21:08 UTC, ericgaspar commented on README_fr.md
> +Merci de faire vos pull request sur la [branche testing](https://github.com/YunoHost-Apps/REPLACEBYYOURAPP_ynh/tree/testing).
```suggestion
Merci de faire vos pull request sur la [branche testing](https://github.com/YunoHost-Apps/funkwhale_ynh/tree/testing).
```

2020-12-14 22:03 UTC, ericgaspar approved these changes

2020-12-19 12:47 UTC, ericgaspar requested changes
Let's change "Install with YunoHost" badge to SVG version

2020-12-19 12:47 UTC, ericgaspar commented on README.md
>  [![Install Funkwhale with YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=funkwhale)
```suggestion
[![Install Funkwhale with YunoHost](https://install-app.yunohost.org/install-with-yunohost.svg)](https://install-app.yunohost.org/?app=funkwhale)
```

2020-12-19 12:47 UTC, ericgaspar commented on README_fr.md
> +[![Install Funkwhale with YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=funkwhale)
```suggestion
[![Install Funkwhale with YunoHost](https://install-app.yunohost.org/install-with-yunohost.svg)](https://install-app.yunohost.org/?app=funkwhale)
```

2020-12-19 18:54 UTC, Thovi98 commented on README_fr.md
> +[![Install Funkwhale with YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=funkwhale)
Yes, it’s far better !!

2020-12-19 19:09 UTC, ericgaspar approved these changes

2020-12-19 22:34 UTC, Sporiff approved these changes

2020-12-20 00:08 UTC, merged