Uprade to 1.1 and fixes Twisted by retrograding it
YunoHost-Apps/funkwhale_ynh pull request #129
Opened 2021-03-10 12:51 UTC by Thovi98

- Upgrade to 1.1

- Fixes Twisted by retrograding it (cf. https://forum.yunohost.org/t/funkwhale-server-crash/14774/2)

Tested install, but not upgrade.

2021-03-10 14:04 UTC, ericgaspar commented
!testme

2021-03-10 15:25 UTC, Sporiff requested changes
In the base requirements, we should also replace line 52 with `git+https://github.com/agateblue/requests-http-signature.git@signature-header-support` to reflect the location change. In theory it should automatically resolve but it's better to be neat about it. As long as everything aligns with [upstream](https://dev.funkwhale.audio/funkwhale/funkwhale/-/blob/master/api/requirements/base.txt) this should be fine

Apart from that and my comment on the watchdog line this looks fine to me. I don't have time right now to test this (currently in the middle of moving country) but if somebody wants to give it a try that would be great 👍

2021-03-10 15:25 UTC, Sporiff commented on sources/extra_files/app/api/requirements/base.txt
> +watchdog~=0.10
I think this needs to be bumped to 1.0.2 in line with upstream

2021-03-10 15:33 UTC, Thovi98 commented
I’ve copy pasted the upstream file, and checked, now everything is fine I think. 

I had tested it already, works great !

2021-03-11 18:52 UTC, ericgaspar commented
Is this PR ready to be merged? 👀

2021-03-11 19:00 UTC, Thovi98 commented
From my side, it is, and @Sporiff approuved, so I think it’s okay

2021-03-11 19:03 UTC, merged

2021-03-11 19:04 UTC, ericgaspar commented
Merging as the app is level 0. 👍🏻