Patch
YunoHost-Apps/funkwhale_ynh pull request #156
Opened 2021-09-25 13:43 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2021-09-25 13:44 UTC, ericgaspar commented
!testme

2021-11-01 12:59 UTC, ericgaspar commented
!testme

2021-11-04 19:10 UTC, yalh76 requested changes

2021-11-04 19:10 UTC, yalh76 commented on conf/nginx.conf
> +location /_protected/media/ {
I'm not sure that adding `/` would work, i've removed it during https://github.com/YunoHost-Apps/funkwhale_ynh/pull/138/files#diff-8e371ad49c2a106a2f6b14d3cb01445c4f7d5c3694f50892d95932b48f42671c

2021-11-04 19:10 UTC, yalh76 commented on conf/nginx.conf
> +location /_protected/music/ {
I'm not sure that adding `/` would work, i've removed it during https://github.com/YunoHost-Apps/funkwhale_ynh/pull/138/files#diff-8e371ad49c2a106a2f6b14d3cb01445c4f7d5c3694f50892d95932b48f42671c

2021-11-04 19:10 UTC, yalh76 commented on scripts/install
> +ynh_app_setting_set --app=$app --key=datadir --value=$datadir
Not sure that this would work, it seems that previously, datadir was saved as `/home/yunohost.app/$app` instead of `/home/yunohost.app/${app}/data`

It seems that I made that mismatch... And I don't know if files are in the datadir or in datadir/data :/

2021-11-04 19:10 UTC, yalh76 commented on scripts/install
> +ynh_psql_setup_db --db_user=$db_name --db_name=$db_name
```suggestion
ynh_psql_setup_db --db_user=$db_user --db_name=$db_name
```

2021-11-21 18:53 UTC, alexAubin commented
(Bumpitybump in case somebody has time to iterate on that review)

2021-11-21 19:07 UTC, ericgaspar commented
!testme

2021-12-12 16:11 UTC, ericgaspar commented
!tastemetitus

2022-01-01 10:16 UTC, Thovi98 commented on conf/nginx.conf
> +location /_protected/music/ {
Interrestingly, I’ve just tried an install with the `fix/NGINX` branch
`sudo yunohost app install https://github.com/yunohost-apps/funkwhale_ynh/tree/fix-NGINX --debug -f`

and it works great ! I can play any tracks.

2022-01-05 13:25 UTC, ericgaspar commented
!testme

2022-01-06 09:09 UTC, Thovi98 commented
There are a lot of warnings in the input, but I don’t know if it’s that important to change the behavior, since it only affects 1.2.0 release and probably will be resolved in the next release (https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1663)

2022-01-11 19:18 UTC, closed without merging