Upgrade to 1.2.3
YunoHost-Apps/funkwhale_ynh pull request #171
Opened 2022-03-22 10:58 UTC by Thovi98

## Problem

- New bugfixes release (https://blog.funkwhale.audio/funkwhale-123-release.html)

## Solution

- Upgrade

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-03-22 22:56 UTC, yalh76 commented
!testme

2022-03-22 22:57 UTC, yalh76 approved these changes
Great work, thanks a lot :)

2022-03-23 08:24 UTC, Thovi98 commented
I don't understand why the sha256sum changes every time... Could you have a look please @yalh76 ?

2022-03-23 19:20 UTC, yalh76 requested changes

2022-03-23 19:20 UTC, yalh76 commented on conf/front.src
>  SOURCE_SUM=1cce4f6969afdd9338c464456a5d5eb9ade8a70d72431950baa7acff4197d315
@Thovi98 you forgot to change that checksum :/

Maybe one day we could add the autoupdater => https://github.com/YunoHost/example_ynh/blob/master/.github/workflows/updater.sh

2022-03-23 20:00 UTC, Thovi98 commented on conf/front.src
>  SOURCE_SUM=1cce4f6969afdd9338c464456a5d5eb9ade8a70d72431950baa7acff4197d315
Woops, my bad ! I hope I’ve set the correct one now, thanks 😁

> Maybe one day we could add the autoupdater => https://github.com/YunoHost/example_ynh/blob/master/.github/workflows/updater.sh

Yes it would be cool ! But I don’t understand the Github workflow language yet... Anyway, I don’t mind continue help updating like now, it’s good for learning how everything works 👍

2022-03-23 23:34 UTC, yalh76 approved these changes

2022-03-24 01:39 UTC, merged